[package]
name = "HW-11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
group = "*"
integer-sqrt = "*"
num-modular = "*"
modinverse = "*"
bubblemath = "*"
modpow = "*"
num = "*"